### ISSUE TITLE
pyhfst does not return the same results as hfst

### ISSUE THREAD

**Issue by bowersd** [Rootroo-ltd/pyhfst#6] opened 2024-03-17 17:19 UTC
As described in the header, pyhfst lookup() does not return the same results as hfst ... I got as far as looking at the definition for analyze(), which returns [] if  self.state.input_string[0] == NO_SYMBOL_NUMBER. But I have to go. See the screenshot for evidence of the difference in behavior:

![image](https://github.com/Rootroo-ltd/pyhfst/assets/6401700/f6b9ed65-046b-43e3-9e56-6d93af3424a2)

**Comment by bowersd** [comment] 2024-03-17 17:20
I cannot attach my analyzer, but you can find it at https://github.com/bowersd/textAnalysis

**Comment by mokha** [comment] 2024-03-26 20:34
The issue is fixed in the release 1.3.0. Consider staring the project if you're finding it useful.

**Closed by mokha** 2024-03-26 20:34 UTC
